### ISSUE TITLE
Not using mock data on iOS 9/Xcode 7 beta

### ISSUE THREAD

**Issue by stephenwoodford** [vokal/VOKMockUrlProtocol#29] opened 2015-08-12 15:37 UTC
Running tests on Xcode 7 beta 5 with an iOS 9 simulator will not use the mock data, API requests are always used. This can be confirmed by turning off Internet connectivity and seeing all of the mock data tests fail.

Tested the same project on Xcode 6.4 with an iOS 8.4 simulator and the mock data is used. Was not able to test using Xcode 7 with an iOS 8.4 simulator because of a bug with the Xcode beta (https://forums.developer.apple.com/message/39140).

No errors are reported.

**Comment by designatednerd** [comment] 2015-08-12 17:29
Hey @stephenwoodford  - When you log out the list of URL protocol classes on Xcode 6 vs 7, are you still seeing `VOKMockUrlProtocol` in both? Is it in the same place in the order of the protocol classes?

**Comment by stephenwoodford** [comment] 2015-08-12 18:06
Yes, same list on both Xcode 6 and 7. Seems like Apple may have changed the way protocol selection is done in iOS 9.

```
(
    VOKMockUrlProtocol,
    "_NSURLHTTPProtocol",
    "_NSURLDataProtocol",
    "_NSURLFTPProtocol",
    "_NSURLFileProtocol",
    NSAboutURLProtocol
)
```

**Comment by stephenwoodford** [comment] 2015-08-12 18:16
Did a bit more debugging for some more data:

I set a breakpoint at https://github.com/vokal/VOKMockUrlProtocol/blob/master/VOKMockUrlProtocol.m#L54 to see if the protocol was ever being called. Then I changed the index the mockURLProtocol was inserted at all possible locations (0-5),
`[currentProtocolClasses insertObject:mockURLProtocol atIndex:0];`

The breakpoint was never hit so it seems it may be a bug in NSURLSessionConfiguration on iOS 9. Has anyone else run into this problem? If so, I'll submit a bug to Apple about it.

**Comment by designatednerd** [comment] 2015-08-12 19:04
We haven't seen it on our end yet, but we're not doing any 9-only development yet. I'd consult the API diffs to see if they mention anything specific, but otherwise, yeah, I'd say fire a radar (please feel free to link it back here when you post it on OpenRadar!)

**Comment by designatednerd** [comment] 2015-10-05 21:16
@stephenwoodford Did this ever resolve for Xcode 7?

**Comment by stephenwoodford** [comment] 2015-10-06 14:20
@designatednerd This is still an issue on Xcode 7.0.1.

**Comment by designatednerd** [comment] 2015-10-06 14:36
Thank you for the heads up - we'll investigate.

**Comment by designatednerd** [comment] 2015-10-07 14:48
Hey @stephenwoodford  - I was able to get this to work (we're using AFNetworking) with this code, assuming `sessionConfiguration` is the current `NSURLSessionConfiguration` passed in from AFNetworking:

```
    Class mockURLProtocol = [VOKMockUrlProtocol class];
    NSMutableArray *currentProtocolClasses = [sessionConfiguration.protocolClasses mutableCopy] ?: [NSMutableArray array];
    [currentProtocolClasses insertObject:mockURLProtocol atIndex:0];
    sessionConfiguration.protocolClasses = currentProtocolClasses;

   [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:APIBaseURL]
                                                  sessionConfiguration:sessionConfiguration];
```

Hope that helps, but this is definitely working for me on Xcode 7.0.1. If you can verify this helps, I'll try to update the documentation.

**Comment by designatednerd** [comment] 2015-10-08 15:38
@stephenwoodford FYI, I just pushed a version which allows you to pass in a bundle - if you're using this project as a framework, this is necessary because otherwise it looks in the framework's bundle rather than the test bundle. 

I'm gonna go ahead and close this out since I've got this working for both Obj-C and Swift in 7.0.1, but please ping me via email at [github handle] at gmail if you want me to take a look at your setup and see where the issue is.

**Closed by designatednerd** 2015-10-08 15:38 UTC
